import { boolean, index, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const roleName = pgEnum('role_name', ['ADMIN', 'FISCAL_OPERATOR', 'REVIEWER', 'ADVISOR_READONLY']);
export const importStatus = pgEnum('import_status', ['PENDING', 'PROCESSING', 'PREVIEW_READY', 'VALIDATED', 'PARTIALLY_IMPORTED', 'FAILED', 'REPROCESSED']);

const identity = {
  id: uuid('id').primaryKey().defaultRandom(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

export const tenants = pgTable('tenants', { ...identity, name: text('name').notNull(), slug: text('slug').notNull() }, (table) => [uniqueIndex('tenants_slug_uq').on(table.slug)]);
export const legalEntities = pgTable('legal_entities', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalName: text('legal_name').notNull(), countryCode: text('country_code').notNull(), currencyCode: text('currency_code').notNull().default('EUR'), taxIdentityEncrypted: text('tax_identity_encrypted') }, (table) => [index('legal_entities_tenant_idx').on(table.tenantId)]);
export const users = pgTable('users', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), emailEncrypted: text('email_encrypted').notNull(), displayName: text('display_name').notNull(), passwordHash: text('password_hash').notNull(), active: boolean('active').notNull().default(true) }, (table) => [index('users_tenant_idx').on(table.tenantId)]);
export const roles = pgTable('roles', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), name: roleName('name').notNull(), description: text('description').notNull() });
export const permissions = pgTable('permissions', { ...identity, key: text('key').notNull(), description: text('description').notNull() }, (table) => [uniqueIndex('permissions_key_uq').on(table.key)]);
export const userRoles = pgTable('user_roles', { userId: uuid('user_id').notNull().references(() => users.id), roleId: uuid('role_id').notNull().references(() => roles.id) }, (table) => [uniqueIndex('user_roles_uq').on(table.userId, table.roleId)]);
export const auditEvents = pgTable('audit_events', { id: uuid('id').primaryKey().defaultRandom(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id), actorId: uuid('actor_id').references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), metadata: jsonb('metadata').notNull().default({}), ipHash: text('ip_hash'), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [index('audit_tenant_time_idx').on(table.tenantId, table.occurredAt)]);
export const fiscalConfigurations = pgTable('fiscal_configurations', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalEntityId: uuid('legal_entity_id').notNull().references(() => legalEntities.id), label: text('label').notNull(), version: text('version').notNull(), effectiveFrom: timestamp('effective_from', { withTimezone: true }).notNull(), settings: jsonb('settings').notNull(), isDemo: boolean('is_demo').notNull().default(false) });
export const invoiceSeries = pgTable('invoice_series', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalEntityId: uuid('legal_entity_id').notNull().references(() => legalEntities.id), code: text('code').notNull(), nextNumber: numeric('next_number', { precision: 20, scale: 0 }).notNull().default('1'), documentType: text('document_type').notNull() }, (table) => [uniqueIndex('invoice_series_scope_uq').on(table.legalEntityId, table.code)]);
export const importJobs = pgTable('import_jobs', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), status: importStatus('status').notNull().default('PENDING'), connectorId: text('connector_id'), mappingVersion: text('mapping_version'), requestedBy: uuid('requested_by').references(() => users.id), summary: jsonb('summary').notNull().default({}) }, (table) => [index('import_jobs_tenant_status_idx').on(table.tenantId, table.status)]);
export const importFiles = pgTable('import_files', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importJobId: uuid('import_job_id').notNull().references(() => importJobs.id), storageKey: text('storage_key').notNull(), originalNameEncrypted: text('original_name_encrypted').notNull(), mimeType: text('mime_type').notNull(), byteSize: numeric('byte_size', { precision: 20, scale: 0 }).notNull(), sha256: text('sha256').notNull(), importerVersion: text('importer_version').notNull() }, (table) => [uniqueIndex('import_files_tenant_hash_uq').on(table.tenantId, table.sha256)]);
export const importRows = pgTable('import_rows', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), rowNumber: numeric('row_number', { precision: 12, scale: 0 }).notNull(), status: text('status').notNull(), rawEncrypted: text('raw_encrypted').notNull(), normalized: jsonb('normalized').notNull().default({}), businessKey: text('business_key') }, (table) => [index('import_rows_file_idx').on(table.importFileId)]);
export const importErrors = pgTable('import_errors', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importJobId: uuid('import_job_id').notNull().references(() => importJobs.id), importRowId: uuid('import_row_id').references(() => importRows.id), code: text('code').notNull(), severity: text('severity').notNull(), message: text('message').notNull(), blocking: boolean('blocking').notNull().default(false) });
export const evidenceDocuments = pgTable('evidence_documents', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), sourceChannel: text('source_channel').notNull(), documentType: text('document_type').notNull(), storageKey: text('storage_key').notNull(), sha256: text('sha256').notNull(), immutable: boolean('immutable').notNull().default(true), capturedAt: timestamp('captured_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [index('evidence_tenant_hash_idx').on(table.tenantId, table.sha256)]);
export const commercialOrders = pgTable('commercial_orders', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), sourceChannel: text('source_channel').notNull(), externalOrderId: text('external_order_id').notNull(), checkoutReference: text('checkout_reference'), commercialDate: timestamp('commercial_date', { withTimezone: true }), evidenceDocumentId: uuid('evidence_document_id').references(() => evidenceDocuments.id), customerCountry: text('customer_country'), customerType: text('customer_type'), productNature: text('product_nature'), customerName: text('customer_name'), totalAmount: numeric('total_amount', { precision: 20, scale: 6 }), taxAmount: numeric('tax_amount', { precision: 20, scale: 6 }), customerEmail: text('customer_email'), customerAddress: text('customer_address') }, (table) => [uniqueIndex('orders_external_uq').on(table.tenantId, table.sourceChannel, table.externalOrderId)]);
export const financialEvents = pgTable('financial_events', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), sourceChannel: text('source_channel').notNull(), externalEventId: text('external_event_id').notNull(), eventType: text('event_type').notNull(), orderReference: text('order_reference'), checkoutReference: text('checkout_reference'), amount: numeric('amount', { precision: 20, scale: 6 }).notNull(), feeAmount: numeric('fee_amount', { precision: 20, scale: 6 }).notNull(), netAmount: numeric('net_amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull() }, (table) => [uniqueIndex('financial_events_external_uq').on(table.tenantId, table.sourceChannel, table.externalEventId)]);
export const canonicalOperations = pgTable('canonical_operations', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalEntityId: uuid('legal_entity_id').notNull().references(() => legalEntities.id), sourceChannel: text('source_channel').notNull(), sourceOrderId: text('source_order_id'), operationType: text('operation_type').notNull(), operationStatus: text('operation_status').notNull(), originalCurrency: text('original_currency'), grossAmount: numeric('gross_amount', { precision: 20, scale: 6 }), platformFeeAmount: numeric('platform_fee_amount', { precision: 20, scale: 6 }), netAmount: numeric('net_amount', { precision: 20, scale: 6 }), reviewStatus: text('review_status').notNull(), reconciliationStatus: text('reconciliation_status').notNull(), verifactuStatus: text('verifactu_status').notNull(), anomalyFlags: text('anomaly_flags').array().notNull().default([]), customerCountry: text('customer_country'), customerType: text('customer_type'), productNature: text('product_nature'), customerEmail: text('customer_email'), customerAddress: text('customer_address') }, (table) => [index('operations_tenant_status_idx').on(table.tenantId, table.operationStatus), uniqueIndex('canonical_operations_tenant_source_uq').on(table.tenantId, table.sourceChannel, table.sourceOrderId)]);
export const matchingCandidates = pgTable('matching_candidates', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), commercialOrderId: uuid('commercial_order_id').notNull().references(() => commercialOrders.id), financialEventId: uuid('financial_event_id').notNull().references(() => financialEvents.id), confidence: numeric('confidence', { precision: 5, scale: 4 }).notNull(), explanation: jsonb('explanation').notNull(), accepted: boolean('accepted').notNull().default(false) }, (table) => [uniqueIndex('matching_candidates_tenant_order_event_uq').on(table.tenantId, table.commercialOrderId, table.financialEventId)]);
export const issues = pgTable('issues', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), canonicalOperationId: uuid('canonical_operation_id').references(() => canonicalOperations.id), code: text('code').notNull(), severity: text('severity').notNull(), status: text('status').notNull().default('OPEN'), title: text('title').notNull(), explanation: text('explanation').notNull() }, (table) => [index('issues_tenant_status_idx').on(table.tenantId, table.status)]);
export const taxDecisions = pgTable('tax_decisions', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), canonicalOperationId: uuid('canonical_operation_id').notNull().references(() => canonicalOperations.id), ruleId: text('rule_id'), ruleVersion: text('rule_version'), status: text('status').notNull(), taxBase: numeric('tax_base', { precision: 20, scale: 6 }), taxRate: numeric('tax_rate', { precision: 10, scale: 6 }), taxAmount: numeric('tax_amount', { precision: 20, scale: 6 }), totalAmount: numeric('total_amount', { precision: 20, scale: 6 }), explanation: jsonb('explanation').notNull(), decidedAt: timestamp('decided_at', { withTimezone: true }).notNull().defaultNow() });
export const fiscalDocuments = pgTable('fiscal_documents', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), canonicalOperationId: uuid('canonical_operation_id').notNull().references(() => canonicalOperations.id), number: text('number').notNull(), documentType: text('document_type').notNull(), status: text('status').notNull(), originalDocumentId: uuid('original_document_id'), issuedAt: timestamp('issued_at', { withTimezone: true }).notNull(), taxBase: numeric('tax_base', { precision: 20, scale: 6 }).notNull(), taxAmount: numeric('tax_amount', { precision: 20, scale: 6 }).notNull(), totalAmount: numeric('total_amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), renderStorageKey: text('render_storage_key').notNull(), renderSha256: text('render_sha256').notNull(), locked: boolean('locked').notNull().default(true) }, (table) => [uniqueIndex('fiscal_document_number_uq').on(table.tenantId, table.number)]);
export const integrityChainRecords = pgTable('integrity_chain_records', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), fiscalDocumentId: uuid('fiscal_document_id').notNull().references(() => fiscalDocuments.id), recordType: text('record_type').notNull(), canonicalPayload: text('canonical_payload').notNull(), previousHash: text('previous_hash'), hash: text('hash').notNull(), algorithm: text('algorithm').notNull().default('SHA-256') }, (table) => [uniqueIndex('integrity_hash_uq').on(table.tenantId, table.hash)]);
export const verifactuSubmissions = pgTable('verifactu_submissions', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), integrityRecordId: uuid('integrity_record_id').notNull().references(() => integrityChainRecords.id), environment: text('environment').notNull(), status: text('status').notNull(), payloadRedacted: jsonb('payload_redacted').notNull(), responseRedacted: jsonb('response_redacted'), attemptCount: numeric('attempt_count', { precision: 8, scale: 0 }).notNull().default('0') });
export const periodCloses = pgTable('period_closes', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), period: text('period').notNull(), status: text('status').notNull(), frozenAt: timestamp('frozen_at', { withTimezone: true }), approvedBy: uuid('approved_by').references(() => users.id), blockingApprovalId: uuid('blocking_approval_id') }, (table) => [uniqueIndex('period_close_uq').on(table.tenantId, table.period)]);
export const vatDossiers = pgTable('vat_dossiers', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), periodCloseId: uuid('period_close_id').notNull().references(() => periodCloses.id), schemaVersion: text('schema_version').notNull(), status: text('status').notNull(), storageKey: text('storage_key').notNull(), archiveSha256: text('archive_sha256').notNull(), manifest: jsonb('manifest').notNull() });
export const royaltyStatements = pgTable('royalty_statements', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), sourceConnector: text('source_connector').notNull(), currency: text('currency').notNull(), periods: text('periods').array().notNull().default([]), totalRoyalties: numeric('total_royalties', { precision: 20, scale: 6 }).notNull(), lineCount: numeric('line_count', { precision: 12, scale: 0 }).notNull(), hash: text('hash').notNull() }, (table) => [uniqueIndex('royalty_statements_tenant_hash_uq').on(table.tenantId, table.hash)]);
export const royaltyLines = pgTable('royalty_lines', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), royaltyStatementId: uuid('royalty_statement_id').notNull().references(() => royaltyStatements.id), businessKey: text('business_key').notNull(), classification: text('classification').notNull(), status: text('status').notNull(), period: text('period').notNull(), title: text('title'), isbnOrAsin: text('isbn_or_asin').notNull(), store: text('store'), unitsSold: numeric('units_sold', { precision: 12, scale: 0 }), unitsReturned: numeric('units_returned', { precision: 12, scale: 0 }), unitsNet: numeric('units_net', { precision: 12, scale: 0 }), amount: numeric('amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), averageUnitPrice: numeric('average_unit_price', { precision: 20, scale: 6 }), productionCost: numeric('production_cost', { precision: 20, scale: 6 }), kenpPages: numeric('kenp_pages', { precision: 12, scale: 0 }), sourceSheet: text('source_sheet').notNull() }, (table) => [uniqueIndex('royalty_lines_tenant_key_uq').on(table.tenantId, table.businessKey), index('royalty_lines_statement_idx').on(table.royaltyStatementId)]);
