import { boolean, date, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const roleName = pgEnum('role_name', ['ADMIN', 'FISCAL_OPERATOR', 'REVIEWER', 'ADVISOR_READONLY']);
// FASE 03: ANALYZED/PENDING_CONFIRMATION/IMPORTED/IMPORTED_WITH_ISSUES/REJECTED
// are additive (see migrations/0012_import_states_v2.sql). Old values remain
// valid for reading pre-FASE-03 rows -- no backfill, no rename.
export const importStatus = pgEnum('import_status', ['PENDING', 'PROCESSING', 'PREVIEW_READY', 'VALIDATED', 'PARTIALLY_IMPORTED', 'FAILED', 'REPROCESSED', 'ANALYZED', 'PENDING_CONFIRMATION', 'IMPORTED', 'IMPORTED_WITH_ISSUES', 'REJECTED']);

const identity = {
  id: uuid('id').primaryKey().defaultRandom(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

export const tenants = pgTable('tenants', { ...identity, name: text('name').notNull(), slug: text('slug').notNull() }, (table) => [uniqueIndex('tenants_slug_uq').on(table.slug)]);
export const legalEntities = pgTable('legal_entities', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalName: text('legal_name').notNull(), tradeName: text('trade_name'), countryCode: text('country_code').notNull(), currencyCode: text('currency_code').notNull().default('EUR'), taxIdentityEncrypted: text('tax_identity_encrypted'), address: text('address'), contactEmail: text('contact_email'), configurationStatus: text('configuration_status').notNull().default('INCOMPLETE'), issuerType: text('issuer_type').notNull().default('PERSONA_FISICA'), iaeCode: text('iae_code'), vatRegime: text('vat_regime').notNull().default('REGIMEN_REDUCIDO_LIBROS_ES'), irpfSettings: jsonb('irpf_settings').notNull().default({}), ossEnabled: boolean('oss_enabled').notNull().default(false), ossEffectiveFrom: date('oss_effective_from'), fiscalConfigurationStatus: text('fiscal_configuration_status').notNull().default('INCOMPLETA'), taxIdentityConfigured: boolean('tax_identity_configured').notNull().default(false) }, (table) => [index('legal_entities_tenant_idx').on(table.tenantId)]);
export const users = pgTable('users', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), emailEncrypted: text('email_encrypted').notNull(), displayName: text('display_name').notNull(), passwordHash: text('password_hash').notNull(), active: boolean('active').notNull().default(true) }, (table) => [index('users_tenant_idx').on(table.tenantId)]);
export const roles = pgTable('roles', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), name: roleName('name').notNull(), description: text('description').notNull() });
export const permissions = pgTable('permissions', { ...identity, key: text('key').notNull(), description: text('description').notNull() }, (table) => [uniqueIndex('permissions_key_uq').on(table.key)]);
export const userRoles = pgTable('user_roles', { userId: uuid('user_id').notNull().references(() => users.id), roleId: uuid('role_id').notNull().references(() => roles.id) }, (table) => [uniqueIndex('user_roles_uq').on(table.userId, table.roleId)]);
export const auditEvents = pgTable('audit_events', { id: uuid('id').primaryKey().defaultRandom(), tenantId: uuid('tenant_id').notNull().references(() => tenants.id), actorId: uuid('actor_id').references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), metadata: jsonb('metadata').notNull().default({}), ipHash: text('ip_hash'), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [index('audit_tenant_time_idx').on(table.tenantId, table.occurredAt)]);
export const fiscalConfigurations = pgTable('fiscal_configurations', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalEntityId: uuid('legal_entity_id').notNull().references(() => legalEntities.id), label: text('label').notNull(), version: text('version').notNull(), effectiveFrom: timestamp('effective_from', { withTimezone: true }).notNull(), settings: jsonb('settings').notNull(), isDemo: boolean('is_demo').notNull().default(false) });
export const invoiceSeries = pgTable('invoice_series', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalEntityId: uuid('legal_entity_id').notNull().references(() => legalEntities.id), code: text('code').notNull(), fiscalYear: integer('fiscal_year'), nextNumber: numeric('next_number', { precision: 20, scale: 0 }).notNull().default('1'), documentType: text('document_type').notNull(), active: boolean('active').notNull().default(true), locked: boolean('locked').notNull().default(false) }, (table) => [uniqueIndex('invoice_series_scope_uq').on(table.legalEntityId, table.code), uniqueIndex('invoice_series_tenant_year_type_uq').on(table.tenantId, table.legalEntityId, table.fiscalYear, table.documentType, table.code)]);
export const importJobs = pgTable('import_jobs', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), status: importStatus('status').notNull().default('PENDING'), connectorId: text('connector_id'), mappingVersion: text('mapping_version'), requestedBy: uuid('requested_by').references(() => users.id), summary: jsonb('summary').notNull().default({}) }, (table) => [index('import_jobs_tenant_status_idx').on(table.tenantId, table.status)]);
export const importFiles = pgTable('import_files', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importJobId: uuid('import_job_id').notNull().references(() => importJobs.id), storageKey: text('storage_key').notNull(), originalNameEncrypted: text('original_name_encrypted').notNull(), mimeType: text('mime_type').notNull(), byteSize: numeric('byte_size', { precision: 20, scale: 0 }).notNull(), sha256: text('sha256').notNull(), importerVersion: text('importer_version').notNull() }, (table) => [uniqueIndex('import_files_tenant_hash_uq').on(table.tenantId, table.sha256)]);
export const importRows = pgTable('import_rows', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), rowNumber: numeric('row_number', { precision: 12, scale: 0 }).notNull(), status: text('status').notNull(), rawEncrypted: text('raw_encrypted').notNull(), normalized: jsonb('normalized').notNull().default({}), businessKey: text('business_key') }, (table) => [index('import_rows_file_idx').on(table.importFileId)]);
export const importErrors = pgTable('import_errors', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importJobId: uuid('import_job_id').notNull().references(() => importJobs.id), importRowId: uuid('import_row_id').references(() => importRows.id), code: text('code').notNull(), severity: text('severity').notNull(), message: text('message').notNull(), blocking: boolean('blocking').notNull().default(false) });
export const evidenceDocuments = pgTable('evidence_documents', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), sourceChannel: text('source_channel').notNull(), documentType: text('document_type').notNull(), storageKey: text('storage_key').notNull(), sha256: text('sha256').notNull(), immutable: boolean('immutable').notNull().default(true), capturedAt: timestamp('captured_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [index('evidence_tenant_hash_idx').on(table.tenantId, table.sha256)]);
export const commercialOrders = pgTable('commercial_orders', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), sourceChannel: text('source_channel').notNull(), externalOrderId: text('external_order_id').notNull(), checkoutReference: text('checkout_reference'), commercialDate: timestamp('commercial_date', { withTimezone: true }), evidenceDocumentId: uuid('evidence_document_id').references(() => evidenceDocuments.id), customerCountry: text('customer_country'), billingCountry: text('billing_country'), shippingCountry: text('shipping_country'), customerType: text('customer_type'), customerTypeEvidenceStatus: text('customer_type_evidence_status').notNull().default('UNKNOWN'), productNature: text('product_nature'), customerName: text('customer_name'), totalAmount: numeric('total_amount', { precision: 20, scale: 6 }), taxAmount: numeric('tax_amount', { precision: 20, scale: 6 }), reportedTaxLabel: text('reported_tax_label'), reportedTaxRate: numeric('reported_tax_rate', { precision: 10, scale: 6 }), customerEmail: text('customer_email'), customerAddress: text('customer_address'), paymentStatus: text('payment_status').notNull().default('UNKNOWN'), refundStatus: text('refund_status').notNull().default('NONE'), fiscalStatus: text('fiscal_status').notNull().default('PENDING'), financialStatus: text('financial_status'), fulfillmentStatus: text('fulfillment_status'), paidAt: timestamp('paid_at', { withTimezone: true }), fulfilledAt: timestamp('fulfilled_at', { withTimezone: true }), cancelledAt: timestamp('cancelled_at', { withTimezone: true }), discountCode: text('discount_code'), discountAmount: numeric('discount_amount', { precision: 20, scale: 6 }), shippingAmount: numeric('shipping_amount', { precision: 20, scale: 6 }), reportedSubtotalAmount: numeric('reported_subtotal_amount', { precision: 20, scale: 6 }), reportedTotalAmount: numeric('reported_total_amount', { precision: 20, scale: 6 }), sourceImportFileId: uuid('source_import_file_id').references(() => importFiles.id) }, (table) => [uniqueIndex('orders_external_uq').on(table.tenantId, table.sourceChannel, table.externalOrderId)]);
export const financialEvents = pgTable('financial_events', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), sourceChannel: text('source_channel').notNull(), externalEventId: text('external_event_id').notNull(), eventType: text('event_type').notNull(), orderReference: text('order_reference'), checkoutReference: text('checkout_reference'), amount: numeric('amount', { precision: 20, scale: 6 }).notNull(), feeAmount: numeric('fee_amount', { precision: 20, scale: 6 }).notNull(), netAmount: numeric('net_amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull() }, (table) => [uniqueIndex('financial_events_external_uq').on(table.tenantId, table.sourceChannel, table.externalEventId)]);
export const canonicalOperations = pgTable('canonical_operations', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalEntityId: uuid('legal_entity_id').notNull().references(() => legalEntities.id), sourceChannel: text('source_channel').notNull(), sourceOrderId: text('source_order_id'), operationType: text('operation_type').notNull(), operationStatus: text('operation_status').notNull(), originalCurrency: text('original_currency'), grossAmount: numeric('gross_amount', { precision: 20, scale: 6 }), platformFeeAmount: numeric('platform_fee_amount', { precision: 20, scale: 6 }), netAmount: numeric('net_amount', { precision: 20, scale: 6 }), reviewStatus: text('review_status').notNull(), reconciliationStatus: text('reconciliation_status').notNull(), verifactuStatus: text('verifactu_status').notNull(), anomalyFlags: text('anomaly_flags').array().notNull().default([]), customerCountry: text('customer_country'), customerType: text('customer_type'), productNature: text('product_nature'), customerEmail: text('customer_email'), customerAddress: text('customer_address') }, (table) => [index('operations_tenant_status_idx').on(table.tenantId, table.operationStatus), uniqueIndex('canonical_operations_tenant_source_uq').on(table.tenantId, table.sourceChannel, table.sourceOrderId)]);
export const matchingCandidates = pgTable('matching_candidates', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), commercialOrderId: uuid('commercial_order_id').notNull().references(() => commercialOrders.id), financialEventId: uuid('financial_event_id').notNull().references(() => financialEvents.id), confidence: numeric('confidence', { precision: 5, scale: 4 }).notNull(), explanation: jsonb('explanation').notNull(), accepted: boolean('accepted').notNull().default(false) }, (table) => [uniqueIndex('matching_candidates_tenant_order_event_uq').on(table.tenantId, table.commercialOrderId, table.financialEventId)]);
export const issues = pgTable('issues', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), canonicalOperationId: uuid('canonical_operation_id').references(() => canonicalOperations.id), code: text('code').notNull(), severity: text('severity').notNull(), status: text('status').notNull().default('OPEN'), title: text('title').notNull(), explanation: text('explanation').notNull() }, (table) => [index('issues_tenant_status_idx').on(table.tenantId, table.status)]);
export const taxDecisions = pgTable('tax_decisions', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), canonicalOperationId: uuid('canonical_operation_id').notNull().references(() => canonicalOperations.id), ruleId: text('rule_id'), ruleVersion: text('rule_version'), status: text('status').notNull(), documentType: text('document_type').notNull().default('COMPLETA'), taxBase: numeric('tax_base', { precision: 20, scale: 6 }), taxRate: numeric('tax_rate', { precision: 10, scale: 6 }), taxAmount: numeric('tax_amount', { precision: 20, scale: 6 }), totalAmount: numeric('total_amount', { precision: 20, scale: 6 }), explanation: jsonb('explanation').notNull(), decidedAt: timestamp('decided_at', { withTimezone: true }).notNull().defaultNow() });
export const fiscalDocuments = pgTable('fiscal_documents', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), canonicalOperationId: uuid('canonical_operation_id').notNull().references(() => canonicalOperations.id), number: text('number').notNull(), documentType: text('document_type').notNull(), status: text('status').notNull(), originalDocumentId: uuid('original_document_id'), issuedAt: timestamp('issued_at', { withTimezone: true }).notNull(), taxBase: numeric('tax_base', { precision: 20, scale: 6 }).notNull(), taxAmount: numeric('tax_amount', { precision: 20, scale: 6 }).notNull(), totalAmount: numeric('total_amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), renderStorageKey: text('render_storage_key').notNull(), renderSha256: text('render_sha256').notNull(), locked: boolean('locked').notNull().default(true) }, (table) => [uniqueIndex('fiscal_document_number_uq').on(table.tenantId, table.number), uniqueIndex('fiscal_document_operation_type_uq').on(table.tenantId, table.canonicalOperationId, table.documentType)]);
export const integrityChainRecords = pgTable('integrity_chain_records', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), fiscalDocumentId: uuid('fiscal_document_id').notNull().references(() => fiscalDocuments.id), recordType: text('record_type').notNull(), canonicalPayload: text('canonical_payload').notNull(), previousHash: text('previous_hash'), hash: text('hash').notNull(), algorithm: text('algorithm').notNull().default('SHA-256') }, (table) => [uniqueIndex('integrity_hash_uq').on(table.tenantId, table.hash)]);
export const verifactuSubmissions = pgTable('verifactu_submissions', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), integrityRecordId: uuid('integrity_record_id').notNull().references(() => integrityChainRecords.id), environment: text('environment').notNull(), status: text('status').notNull(), payloadRedacted: jsonb('payload_redacted').notNull(), responseRedacted: jsonb('response_redacted'), attemptCount: numeric('attempt_count', { precision: 8, scale: 0 }).notNull().default('0') }, (table) => [uniqueIndex('verifactu_submissions_integrity_record_uq').on(table.tenantId, table.integrityRecordId)]);
export const verifactuSubmissionAttempts = pgTable('verifactu_submission_attempts', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), verifactuSubmissionId: uuid('verifactu_submission_id').notNull().references(() => verifactuSubmissions.id), attemptNumber: numeric('attempt_number', { precision: 8, scale: 0 }).notNull(), status: text('status').notNull(), responseRedacted: jsonb('response_redacted').notNull(), attemptedAt: timestamp('attempted_at', { withTimezone: true }).notNull() }, (table) => [uniqueIndex('verifactu_submission_attempts_number_uq').on(table.tenantId, table.verifactuSubmissionId, table.attemptNumber), index('verifactu_submission_attempts_submission_idx').on(table.tenantId, table.verifactuSubmissionId), index('verifactu_submission_attempts_time_idx').on(table.tenantId, table.attemptedAt)]);
export const periodCloses = pgTable('period_closes', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), period: text('period').notNull(), status: text('status').notNull(), frozenAt: timestamp('frozen_at', { withTimezone: true }), approvedBy: uuid('approved_by').references(() => users.id), blockingApprovalId: uuid('blocking_approval_id') }, (table) => [uniqueIndex('period_close_uq').on(table.tenantId, table.period)]);
export const vatDossiers = pgTable('vat_dossiers', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), periodCloseId: uuid('period_close_id').notNull().references(() => periodCloses.id), schemaVersion: text('schema_version').notNull(), status: text('status').notNull(), storageKey: text('storage_key').notNull(), archiveSha256: text('archive_sha256').notNull(), manifest: jsonb('manifest').notNull() });
export const royaltyStatements = pgTable('royalty_statements', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), sourceConnector: text('source_connector').notNull(), currency: text('currency').notNull(), periods: text('periods').array().notNull().default([]), totalRoyalties: numeric('total_royalties', { precision: 20, scale: 6 }).notNull(), lineCount: numeric('line_count', { precision: 12, scale: 0 }).notNull(), hash: text('hash').notNull(), accountingPolicy: text('accounting_policy').notNull().default('NET_ROYALTY_ONLY'), embeddedCostTreatment: text('embedded_cost_treatment').notNull().default('INCLUDED_IN_NET'), status: text('status').notNull().default('IMPORTED') }, (table) => [uniqueIndex('royalty_statements_tenant_hash_uq').on(table.tenantId, table.hash)]);
export const royaltyLines = pgTable('royalty_lines', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), royaltyStatementId: uuid('royalty_statement_id').notNull().references(() => royaltyStatements.id), businessKey: text('business_key').notNull(), classification: text('classification').notNull(), status: text('status').notNull(), period: text('period').notNull(), title: text('title'), isbnOrAsin: text('isbn_or_asin').notNull(), store: text('store'), unitsSold: numeric('units_sold', { precision: 12, scale: 0 }), unitsReturned: numeric('units_returned', { precision: 12, scale: 0 }), unitsNet: numeric('units_net', { precision: 12, scale: 0 }), amount: numeric('amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), averageUnitPrice: numeric('average_unit_price', { precision: 20, scale: 6 }), productionCost: numeric('production_cost', { precision: 20, scale: 6 }), kenpPages: numeric('kenp_pages', { precision: 12, scale: 0 }), sourceSheet: text('source_sheet').notNull() }, (table) => [uniqueIndex('royalty_lines_tenant_key_uq').on(table.tenantId, table.businessKey), index('royalty_lines_statement_idx').on(table.royaltyStatementId)]);

export const productTaxProfiles = pgTable('product_tax_profiles', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), legalEntityId: uuid('legal_entity_id').notNull().references(() => legalEntities.id), selector: text('selector').notNull(), productNature: text('product_nature').notNull(), invoiceDescription: text('invoice_description').notNull(), domesticTaxCode: text('domestic_tax_code').notNull(), domesticTaxRate: numeric('domestic_tax_rate', { precision: 10, scale: 6 }).notNull(), ossEligible: boolean('oss_eligible').notNull().default(false), shippingRequired: boolean('shipping_required').notNull().default(false), effectiveFrom: date('effective_from').notNull(), effectiveTo: date('effective_to'), active: boolean('active').notNull().default(true) }, (table) => [uniqueIndex('product_tax_profiles_selector_uq').on(table.tenantId, table.legalEntityId, table.selector, table.effectiveFrom), index('product_tax_profiles_active_idx').on(table.tenantId, table.active, table.effectiveFrom)]);
export const channelFiscalPolicies = pgTable('channel_fiscal_policies', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), channel: text('channel').notNull(), version: text('version').notNull(), effectiveFrom: date('effective_from').notNull(), kdpAccountingPolicy: text('kdp_accounting_policy').notNull().default('NET_ROYALTY_ONLY'), embeddedCostTreatment: text('embedded_cost_treatment').notNull().default('INCLUDED_IN_NET'), reviewLevel: text('review_level').notNull().default('REVIEW_REQUIRED'), issuerAttributes: jsonb('issuer_attributes').notNull().default({}), active: boolean('active').notNull().default(true) }, (table) => [uniqueIndex('channel_fiscal_policies_version_uq').on(table.tenantId, table.channel, table.version)]);
export const fiscalCounterparties = pgTable('fiscal_counterparties', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), displayName: text('display_name').notNull(), legalName: text('legal_name'), companyName: text('company_name'), emailEncrypted: text('email_encrypted'), billingAddressEncrypted: text('billing_address_encrypted'), shippingAddressEncrypted: text('shipping_address_encrypted'), customerType: text('customer_type').notNull().default('UNKNOWN'), taxIdentityEncrypted: text('tax_identity_encrypted'), validationStatus: text('validation_status').notNull().default('UNVALIDATED'), validatedAt: timestamp('validated_at', { withTimezone: true }), validationSource: text('validation_source'), evidenceDocumentId: uuid('evidence_document_id').references(() => evidenceDocuments.id) }, (table) => [index('fiscal_counterparties_tenant_type_idx').on(table.tenantId, table.customerType)]);
export const orderLines = pgTable('order_lines', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), commercialOrderId: uuid('commercial_order_id').notNull().references(() => commercialOrders.id, { onDelete: 'cascade' }), externalLineId: text('external_line_id'), sku: text('sku'), title: text('title').notNull(), quantity: numeric('quantity', { precision: 12, scale: 0 }).notNull(), unitPrice: numeric('unit_price', { precision: 20, scale: 6 }).notNull(), discountAmount: numeric('discount_amount', { precision: 20, scale: 6 }).notNull().default('0'), subtotalAmount: numeric('subtotal_amount', { precision: 20, scale: 6 }).notNull(), reportedTaxAmount: numeric('reported_tax_amount', { precision: 20, scale: 6 }), productTaxProfileId: uuid('product_tax_profile_id').references(() => productTaxProfiles.id), taxProfileSnapshot: jsonb('tax_profile_snapshot').notNull().default({}), sourceLineFingerprint: text('source_line_fingerprint'), sourceRowNumber: integer('source_row_number'), requiresShipping: boolean('requires_shipping'), taxable: boolean('taxable'), reportedTaxLabel: text('reported_tax_label'), reportedTaxRate: numeric('reported_tax_rate', { precision: 10, scale: 6 }) }, (table) => [uniqueIndex('order_lines_external_uq').on(table.tenantId, table.commercialOrderId, table.externalLineId), index('order_lines_order_idx').on(table.commercialOrderId)]);
export const taxPeriods = pgTable('tax_periods', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), periodType: text('period_type').notNull(), label: text('label').notNull(), startDate: date('start_date').notNull(), endDate: date('end_date').notNull(), status: text('status').notNull().default('OPEN'), closedAt: timestamp('closed_at', { withTimezone: true }), reopenedAt: timestamp('reopened_at', { withTimezone: true }) }, (table) => [uniqueIndex('tax_periods_range_uq').on(table.tenantId, table.periodType, table.startDate, table.endDate)]);
export const payouts = pgTable('payouts', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), channel: text('channel').notNull(), externalPayoutId: text('external_payout_id').notNull(), periodStart: date('period_start'), periodEnd: date('period_end'), currency: text('currency').notNull(), grossAmount: numeric('gross_amount', { precision: 20, scale: 6 }), feeAmount: numeric('fee_amount', { precision: 20, scale: 6 }), netAmount: numeric('net_amount', { precision: 20, scale: 6 }).notNull(), status: text('status').notNull().default('IMPORTED') }, (table) => [uniqueIndex('payouts_external_uq').on(table.tenantId, table.channel, table.externalPayoutId)]);
export const payoutAllocations = pgTable('payout_allocations', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), payoutId: uuid('payout_id').notNull().references(() => payouts.id, { onDelete: 'cascade' }), commercialOrderId: uuid('commercial_order_id').references(() => commercialOrders.id), royaltyStatementId: uuid('royalty_statement_id').references(() => royaltyStatements.id), allocatedAmount: numeric('allocated_amount', { precision: 20, scale: 6 }).notNull(), allocationStatus: text('allocation_status').notNull().default('PROPOSED') }, (table) => [index('payout_allocations_payout_idx').on(table.tenantId, table.payoutId)]);

// SHOPIFY-03: order-level payment-transaction evidence (sale/refund/auth/
// capture/void events from the Shopify Order Transactions export). Migration
// 0014 documents why `shopifyOrderName` (Name), not `shopifyOrderId` (the raw
// numeric Order value), is the real join key against
// commercialOrders.externalOrderId -- shopifyOrderId carries no FK meaning.
export const shopifyOrderPaymentEvents = pgTable('shopify_order_payment_events', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), externalEventKey: text('external_event_key').notNull(), commercialOrderId: uuid('commercial_order_id').references(() => commercialOrders.id), shopifyOrderId: text('shopify_order_id').notNull(), shopifyOrderName: text('shopify_order_name').notNull(), kind: text('kind').notNull(), gateway: text('gateway').notNull(), status: text('status').notNull(), amount: numeric('amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), cardType: text('card_type'), paymentMethod: text('payment_method'), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(), sourceRowNumber: integer('source_row_number'), minimizedSnapshot: jsonb('minimized_snapshot').notNull().default({}) }, (table) => [uniqueIndex('shopify_order_payment_events_tenant_key_uq').on(table.tenantId, table.externalEventKey), index('shopify_order_payment_events_tenant_order_name_idx').on(table.tenantId, table.shopifyOrderName), index('shopify_order_payment_events_tenant_commercial_order_idx').on(table.tenantId, table.commercialOrderId)]);

// SHOPIFY-03: platform settlement-ledger evidence (Shopify Payments Ledger
// export) -- distinct from financial_events (the existing matching pipeline).
// `externalPayoutId` presence is what gates whether a real `payouts` row gets
// created by the repository layer (Task 3) -- pending settlement otherwise.
// `platformVatAmount` is stored as-is and MUST NOT be read by any
// fiscal-decision code path.
export const shopifyPaymentsLedgerEntries = pgTable('shopify_payments_ledger_entries', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), importFileId: uuid('import_file_id').notNull().references(() => importFiles.id), externalEntryKey: text('external_entry_key').notNull(), commercialOrderId: uuid('commercial_order_id').references(() => commercialOrders.id), shopifyOrderName: text('shopify_order_name').notNull(), checkoutReference: text('checkout_reference'), entryType: text('entry_type').notNull(), transactionAt: timestamp('transaction_at', { withTimezone: true }), amount: numeric('amount', { precision: 20, scale: 6 }).notNull(), feeAmount: numeric('fee_amount', { precision: 20, scale: 6 }).notNull(), netAmount: numeric('net_amount', { precision: 20, scale: 6 }).notNull(), currency: text('currency').notNull(), presentmentAmount: numeric('presentment_amount', { precision: 20, scale: 6 }), presentmentCurrency: text('presentment_currency'), platformVatAmount: numeric('platform_vat_amount', { precision: 20, scale: 6 }), cardBrand: text('card_brand'), cardSource: text('card_source'), paymentMethod: text('payment_method'), payoutStatus: text('payout_status').notNull(), payoutDate: date('payout_date'), availableOn: date('available_on'), externalPayoutId: text('external_payout_id'), sourceRowNumber: integer('source_row_number'), minimizedSnapshot: jsonb('minimized_snapshot').notNull().default({}) }, (table) => [uniqueIndex('shopify_payments_ledger_entries_tenant_key_uq').on(table.tenantId, table.externalEntryKey), index('shopify_payments_ledger_entries_tenant_order_name_idx').on(table.tenantId, table.shopifyOrderName), index('shopify_payments_ledger_entries_tenant_commercial_order_idx').on(table.tenantId, table.commercialOrderId), index('shopify_payments_ledger_entries_tenant_transaction_idx').on(table.tenantId, table.transactionAt)]);

// SHOPIFY-05: polymorphic evidence relationships. Canonical direction is
// COMMERCIAL_ORDER -> ORDER_TRANSACTION/LEDGER_ENTRY and
// ORDER_TRANSACTION -> LEDGER_ENTRY, which makes idempotency deterministic.
// These rows are evidence only and are intentionally not connected to the
// legacy matching_candidates/canonical_operations pipeline.
export const shopifyEvidenceLinks = pgTable('shopify_evidence_links', { ...identity, tenantId: uuid('tenant_id').notNull().references(() => tenants.id), leftEvidenceType: text('left_evidence_type').notNull(), leftEvidenceId: uuid('left_evidence_id').notNull(), rightEvidenceType: text('right_evidence_type').notNull(), rightEvidenceId: uuid('right_evidence_id').notNull(), linkType: text('link_type').notNull(), confidence: numeric('confidence', { precision: 5, scale: 4 }).notNull(), state: text('state').notNull(), explanationJson: jsonb('explanation_json').notNull().default({}), createdBy: uuid('created_by').references(() => users.id), decidedBy: uuid('decided_by').references(() => users.id), decidedAt: timestamp('decided_at', { withTimezone: true }) }, (table) => [uniqueIndex('shopify_evidence_links_pair_uq').on(table.tenantId, table.linkType, table.leftEvidenceType, table.leftEvidenceId, table.rightEvidenceType, table.rightEvidenceId), index('shopify_evidence_links_tenant_state_idx').on(table.tenantId, table.state, table.createdAt), index('shopify_evidence_links_left_idx').on(table.tenantId, table.leftEvidenceType, table.leftEvidenceId), index('shopify_evidence_links_right_idx').on(table.tenantId, table.rightEvidenceType, table.rightEvidenceId)]);
