'use client';
import { useMemo, useState } from 'react';
import { demoSpainConfig, VersionedTaxEngine } from '@anclora/tax-engine';
import { FieldLabel, StatusBadge } from '@anclora/ui';

export function TaxSimulator() {
  const [country, setCountry] = useState('ES'); const [nature, setNature] = useState('ebook'); const [amount, setAmount] = useState('6.99');
  const decision = useMemo(() => new VersionedTaxEngine(demoSpainConfig).evaluate({ issuerCountry: 'ES', ...(country ? { customerCountry: country } : {}), customerType: 'B2C', ...(nature ? { productNature: nature } : {}), channel: 'shopify', operationType: 'sale', evidence: country ? ['country'] : [], grossAmount: Number(amount), currency: 'EUR' }), [amount, country, nature]);
  return <section className="tax-simulator"><form className="tax-form" onSubmit={(event) => event.preventDefault()}><span className="section-index">CONTEXTO</span><FieldLabel htmlFor="customer-country" required>País del cliente</FieldLabel><select id="customer-country" value={country} onChange={(event) => setCountry(event.target.value)}><option value="ES">España</option><option value="FR">Francia</option><option value="">Sin evidencia</option></select><FieldLabel htmlFor="product-nature" required>Naturaleza del producto</FieldLabel><select id="product-nature" value={nature} onChange={(event) => setNature(event.target.value)}><option value="ebook">Ebook</option><option value="general">General</option><option value="">Sin clasificar</option></select><FieldLabel htmlFor="gross-amount" required>Total cobrado (EUR)</FieldLabel><input id="gross-amount" type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></form><article className="tax-decision"><span className="section-index">DECISIÓN</span><StatusBadge tone={decision.status === 'DETERMINED' ? 'info' : decision.status === 'BLOCKED' ? 'blocking' : 'warning'}>{decision.status}</StatusBadge><h2>{decision.classification?.replaceAll('_', ' ') ?? 'Revisión necesaria'}</h2><dl><div><dt>Base imponible</dt><dd>{decision.taxBase?.toFixed(2) ?? '—'} EUR</dd></div><div><dt>Tipo</dt><dd>{decision.rate ? `${Number(decision.rate) * 100} %` : '—'}</dd></div><div><dt>Cuota</dt><dd>{decision.taxAmount?.toFixed(2) ?? '—'} EUR</dd></div></dl><ul>{decision.explanation.map((line) => <li key={line}>{line}</li>)}</ul><small>{decision.ruleVersion ? `Versión ${decision.ruleVersion}` : decision.blockingReason}</small></article></section>;
}
