import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { ReconciliationWorkbench } from './workbench';
afterEach(() => vi.unstubAllGlobals());
const proposed = { id: 'link-1', linkType: 'TRANSACTION_TO_LEDGER', state: 'PROPOSED', confidence: '0.95', explanationJson: { shopifyOrderName: 'AI-1001', fiscalStatus: 'PENDIENTE_REVISION_FISCAL', transactionAmount: 6.99, ledgerNetAmount: 6.64, platformFeeAmount: 0.35, payoutStatus: 'pending', externalPayoutId: null, bankVerified: false } };
describe('ReconciliationWorkbench SHOPIFY-06', () => {
  it('explica el alcance sin afirmar conciliación bancaria', async () => { vi.stubGlobal('fetch', vi.fn(() => Promise.resolve({ ok: true, json: () => Promise.resolve([]) }))); render(<ReconciliationWorkbench />); expect(screen.getByText(/no implica que el banco/)).toBeInTheDocument(); await screen.findByText(/No hay enlaces/); });
  it('muestra propuesta, importes, enlace traducido, payout y estado fiscal', async () => { vi.stubGlobal('fetch', vi.fn(() => Promise.resolve({ ok: true, json: () => Promise.resolve([{ ...proposed, linkType: 'Order to transaction' }]) }))); render(<ReconciliationWorkbench />); await screen.findByText('AI-1001'); expect(screen.getByText('Pedido → transacción')).toBeInTheDocument(); expect(screen.getByText('Payout Shopify pendiente')).toBeInTheDocument(); expect(screen.getByText('Pendiente de revisión fiscal')).toBeInTheDocument(); expect(screen.getByText(/Propuesto · 95%/)).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Confirmar' })).toHaveClass('btn'); });
  it('permite confirmar una propuesta', async () => { const fetchMock = vi.fn((_: string, init?: RequestInit) => Promise.resolve({ ok: true, json: () => Promise.resolve(init?.method === 'PATCH' ? proposed : [proposed]) })); vi.stubGlobal('fetch', fetchMock); render(<ReconciliationWorkbench />); fireEvent.click(await screen.findByRole('button', { name: 'Confirmar' })); await waitFor(() => expect(fetchMock).toHaveBeenCalledWith('/api/v1/shopify/evidence-links/link-1', expect.objectContaining({ method: 'PATCH' }))); });
  it('muestra error de API', async () => { vi.stubGlobal('fetch', vi.fn(() => Promise.resolve({ ok: false, json: () => Promise.resolve({}) }))); render(<ReconciliationWorkbench />); await screen.findByText('No se pudieron obtener los enlaces de evidencia'); });
});
