CREATE TABLE "commercial_orders" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),"tenant_id" uuid NOT NULL REFERENCES "tenants"("id"),"source_channel" text NOT NULL,"external_order_id" text NOT NULL,"checkout_reference" text,"commercial_date" timestamptz,"evidence_document_id" uuid REFERENCES "evidence_documents"("id"));
CREATE UNIQUE INDEX "orders_external_uq" ON "commercial_orders"("tenant_id","source_channel","external_order_id");
CREATE TABLE "financial_events" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),"tenant_id" uuid NOT NULL REFERENCES "tenants"("id"),"source_channel" text NOT NULL,"external_event_id" text NOT NULL,"event_type" text NOT NULL,"order_reference" text,"checkout_reference" text,"amount" numeric(20,6) NOT NULL,"fee_amount" numeric(20,6) NOT NULL,"net_amount" numeric(20,6) NOT NULL,"currency" text NOT NULL,"occurred_at" timestamptz NOT NULL);
CREATE UNIQUE INDEX "financial_events_external_uq" ON "financial_events"("tenant_id","source_channel","external_event_id");
CREATE TABLE "canonical_operations" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),"tenant_id" uuid NOT NULL REFERENCES "tenants"("id"),"legal_entity_id" uuid NOT NULL REFERENCES "legal_entities"("id"),"source_channel" text NOT NULL,"source_order_id" text,"operation_type" text NOT NULL,"operation_status" text NOT NULL,"original_currency" text,"gross_amount" numeric(20,6),"platform_fee_amount" numeric(20,6),"net_amount" numeric(20,6),"review_status" text NOT NULL,"reconciliation_status" text NOT NULL,"verifactu_status" text NOT NULL,"anomaly_flags" text[] NOT NULL DEFAULT '{}');
CREATE INDEX "operations_tenant_status_idx" ON "canonical_operations"("tenant_id","operation_status");
CREATE TABLE "matching_candidates" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),"tenant_id" uuid NOT NULL REFERENCES "tenants"("id"),"commercial_order_id" uuid NOT NULL REFERENCES "commercial_orders"("id"),"financial_event_id" uuid NOT NULL REFERENCES "financial_events"("id"),"confidence" numeric(5,4) NOT NULL,"explanation" jsonb NOT NULL,"accepted" boolean NOT NULL DEFAULT false);
CREATE TABLE "issues" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),"tenant_id" uuid NOT NULL REFERENCES "tenants"("id"),"canonical_operation_id" uuid REFERENCES "canonical_operations"("id"),"code" text NOT NULL,"severity" text NOT NULL,"status" text NOT NULL DEFAULT 'OPEN',"title" text NOT NULL,"explanation" text NOT NULL);
CREATE INDEX "issues_tenant_status_idx" ON "issues"("tenant_id","status");
